### ISSUE TITLE
Bonjour :)

### ISSUE THREAD

**Issue by Julien00859** [Martin-Hayot/Projet-Integration-2023#8]
Bonjour,

Merci pour l'invitation !

Je ne pense pas que vous êtes encore sur le discord, voici le lien au cas où https://discord.gg/8ySfzrUjT Si vous voulez bien vous renommer avec prénom+nom dessus. N'hésitez pas à m'envoyer des messages ou bien à utiliser cette issue si vous voulez entrer en contact avec moi.

Bonne journée,
Julien

**Comment by Martin-Hayot** [comment]
Merci pour votre retour !
